#!/usr/bin/env python3
"""
Generate Makefile for dns-zones repositories.

Outputs a Makefile that uses octodns-gitops CLI tools.
"""

import sys

MAKEFILE_TEMPLATE = """# Generated by octodns-gitops-init
# Do not edit manually - regenerate with: octodns-gitops-init > Makefile

# Verbosity flags (default to quiet for readability)
QUIET ?= 1
DEBUG ?=

# Logging config to suppress specific noisy warnings (e.g., Hetzner SOA)
LOGGING_CONFIG ?= logging.yaml

.DEFAULT_GOAL := help

.PHONY: help validate plan apply drift-check report delegate delegate-ns delegate-ds dnssec ovh-token

help:
\t@echo ""
\t@echo "═══════════════════════════════════════════════════════════════════════"
\t@echo "  DNS Zone Management"
\t@echo "═══════════════════════════════════════════════════════════════════════"
\t@echo ""
\t@echo "Workflow:"
\t@echo "  1. make validate      - Check zone file syntax"
\t@echo "  2. make plan          - Preview changes (DRY-RUN, safe to run)"
\t@echo "  3. make apply         - APPLY CHANGES TO LIVE DNS (destructive!)"
\t@echo ""
\t@echo "Available targets:"
\t@echo "  validate    - Validate zone file syntax"
\t@echo "  plan        - DRY-RUN: Preview what would change (does NOT modify DNS)"
\t@echo "  apply       - APPLY: Actually push changes to DNS providers"
\t@echo "  drift-check - Check if live DNS has drifted from local zones"
\t@echo ""
\t@echo "  report      - Query live nameservers and show consistency report"
\t@echo ""
\t@echo "Delegation & DNSSEC (opt-in zones under 'delegation:' in config.yaml):"
\t@echo "  delegate     - DRY-RUN: preview a step (STEP=ns default, or STEP=ds)"
\t@echo "  delegate-ns  - APPLY the NS delegation cutover only (never touches DNSSEC)"
\t@echo "  delegate-ds  - APPLY DNSSEC DS (separate step; only zones with dnssec: true)"
\t@echo "  dnssec       - Validate DNSSEC delegation (read-only)"
\t@echo "  ovh-token    - Request a scoped OVH consumer key (ENV_PREFIX=OVH_...)"
\t@echo ""
\t@echo "Options:"
\t@echo "  ZONE=example.com.  - Process only this zone (works with plan, apply, drift-check, report, delegate*, dnssec)"
\t@echo "  FORCE=1            - Override 30% safety threshold for apply"
\t@echo "  STEP=ns|ds         - delegate preview step (default ns)"
\t@echo "  SCOPE=             - dnssec scope: delegation (default) | all-signed-targets"
\t@echo "  ENV_PREFIX=        - ovh-token credential env prefix (e.g. OVH_AUTOPS)"
\t@echo "  ALLOW_MANUAL_PENDING=1 - delegate-ns/-ds: treat manual (Gandi) zones as informational"
\t@echo "  DEBUG=1            - Enable debug output"
\t@echo "  QUIET=             - Disable quiet mode (unset QUIET)"
\t@echo "  LOGGING_CONFIG=    - Override logging config file"
\t@echo ""
\t@echo "Examples:"
\t@echo "  make plan                        # Preview all changes"
\t@echo "  make plan ZONE=example.com.      # Preview changes for one zone"
\t@echo "  make apply ZONE=example.com.     # Apply changes for one zone only"
\t@echo "  make apply FORCE=1               # Apply despite safety threshold warnings"
\t@echo "  make apply ZONE=x.com. FORCE=1   # Combine: single zone + force"
\t@echo ""

validate:
\t@QUIET=$(QUIET) DEBUG=$(DEBUG) octodns-gitops-validate --config config.yaml $(if $(LOGGING_CONFIG),--logging-config $(LOGGING_CONFIG),)

# DRY-RUN: Preview changes without applying them
plan: validate
\t@echo ""
\t@echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
\t@echo "  DRY-RUN MODE - Preview only, no changes will be applied"
\t@echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
\t@echo ""
\t@QUIET=$(QUIET) DEBUG=$(DEBUG) octodns-gitops-sync --config config.yaml $(if $(ZONE),--zone $(ZONE),) $(if $(LOGGING_CONFIG),--logging-config $(LOGGING_CONFIG),)
\t@echo ""
\t@echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
\t@echo "  DRY-RUN complete. To apply these changes, run: make apply"
\t@echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
\t@echo ""

# Apply changes from local zones/ to providers
apply: validate
\t@echo ""
\t@echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
\t@echo "  APPLYING CHANGES TO LIVE DNS - This will modify DNS records!"
\t@echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
\t@echo ""
\t@QUIET=$(QUIET) DEBUG=$(DEBUG) octodns-gitops-sync --config config.yaml --doit $(if $(ZONE),--zone $(ZONE),) $(if $(FORCE),--force,) $(if $(LOGGING_CONFIG),--logging-config $(LOGGING_CONFIG),)
\t@echo ""
\t@echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
\t@echo "  Changes applied to live DNS"
\t@echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
\t@echo ""

# Check for drift: fails if live DNS differs from local zones
drift-check:
\t@QUIET=$(QUIET) DEBUG=$(DEBUG) octodns-gitops-drift --config config.yaml $(if $(ZONE),--zone $(ZONE),) $(if $(LOGGING_CONFIG),--logging-config $(LOGGING_CONFIG),)

# Query live DNS and compare with configured source (zones)
report:
\t@QUIET=$(QUIET) DEBUG=$(DEBUG) octodns-gitops-report --config config.yaml $(if $(ZONE),--zone $(ZONE),) $(if $(LOGGING_CONFIG),--logging-config $(LOGGING_CONFIG),)

# Delegation - DRY-RUN preview of a step (STEP=ns default, or STEP=ds); no writes
STEP ?= ns
delegate:
\t@octodns-gitops-delegate --config config.yaml --step $(STEP) $(if $(ZONE),--zone $(ZONE),)

# Delegation - APPLY the NS cutover only (never touches DNSSEC)
delegate-ns:
\t@echo ""
\t@echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
\t@echo "  APPLYING NS DELEGATION CUTOVER (no DNSSEC)"
\t@echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
\t@echo ""
\t@octodns-gitops-delegate --doit --step ns --config config.yaml $(if $(ZONE),--zone $(ZONE),) $(if $(ALLOW_MANUAL_PENDING),--allow-manual-pending,)

# Delegation - APPLY DNSSEC DS (separate step; only zones with dnssec: true)
delegate-ds:
\t@echo ""
\t@echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
\t@echo "  APPLYING DNSSEC DS PUBLICATION"
\t@echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
\t@echo ""
\t@octodns-gitops-delegate --doit --step ds --config config.yaml $(if $(ZONE),--zone $(ZONE),) $(if $(ALLOW_MANUAL_PENDING),--allow-manual-pending,)

# Validate DNSSEC delegation (read-only)
dnssec:
\t@octodns-gitops-dnssec --config config.yaml $(if $(ZONE),--zone $(ZONE),) $(if $(SCOPE),--scope $(SCOPE),)

# Request a least-privilege OVH consumer key (ENV_PREFIX=OVH_AUTOPS)
ovh-token:
\t@octodns-gitops-ovh-token $(if $(ENV_PREFIX),--env-prefix $(ENV_PREFIX),)
"""


def main() -> int:
    """Output Makefile to stdout."""
    print(MAKEFILE_TEMPLATE)
    return 0


if __name__ == "__main__":
    sys.exit(main())
