#!/usr/bin/env python3
"""
Generate Makefile for dns-zones repositories.

Outputs a Makefile that uses octodns-gitops CLI tools.
"""

import sys

MAKEFILE_TEMPLATE = """# Generated by octodns-gitops-init
# Do not edit manually - regenerate with: octodns-gitops-init > Makefile

# Verbosity flags (default to quiet for readability)
QUIET ?= 1
DEBUG ?=

# Logging config to suppress specific noisy warnings (e.g., Hetzner SOA)
LOGGING_CONFIG ?= logging.yaml

.DEFAULT_GOAL := help

.PHONY: help validate plan apply drift-check report

help:
\t@echo ""
\t@echo "═══════════════════════════════════════════════════════════════════════"
\t@echo "  DNS Zone Management"
\t@echo "═══════════════════════════════════════════════════════════════════════"
\t@echo ""
\t@echo "Workflow:"
\t@echo "  1. make validate      - Check zone file syntax"
\t@echo "  2. make plan          - Preview changes (DRY-RUN, safe to run)"
\t@echo "  3. make apply         - APPLY CHANGES TO LIVE DNS (destructive!)"
\t@echo ""
\t@echo "Available targets:"
\t@echo "  validate    - Validate zone file syntax"
\t@echo "  plan        - DRY-RUN: Preview what would change (does NOT modify DNS)"
\t@echo "  apply       - APPLY: Actually push changes to DNS providers"
\t@echo "  drift-check - Check if live DNS has drifted from local zones"
\t@echo ""
\t@echo "  report      - Query live nameservers and show consistency report"
\t@echo ""
\t@echo "Options:"
\t@echo "  ZONE=example.com.  - Process only this zone (works with plan, apply, drift-check, report)"
\t@echo "  FORCE=1            - Override 30% safety threshold for apply"
\t@echo "  DEBUG=1            - Enable debug output"
\t@echo "  QUIET=             - Disable quiet mode (unset QUIET)"
\t@echo "  LOGGING_CONFIG=    - Override logging config file"
\t@echo ""
\t@echo "Examples:"
\t@echo "  make plan                        # Preview all changes"
\t@echo "  make plan ZONE=example.com.      # Preview changes for one zone"
\t@echo "  make apply ZONE=example.com.     # Apply changes for one zone only"
\t@echo "  make apply FORCE=1               # Apply despite safety threshold warnings"
\t@echo "  make apply ZONE=x.com. FORCE=1   # Combine: single zone + force"
\t@echo ""

validate:
\t@QUIET=$(QUIET) DEBUG=$(DEBUG) octodns-gitops-validate --config config.yaml $(if $(LOGGING_CONFIG),--logging-config $(LOGGING_CONFIG),)

# DRY-RUN: Preview changes without applying them
plan: validate
\t@echo ""
\t@echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
\t@echo "  DRY-RUN MODE - Preview only, no changes will be applied"
\t@echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
\t@echo ""
\t@QUIET=$(QUIET) DEBUG=$(DEBUG) octodns-gitops-sync --config config.yaml $(if $(ZONE),--zone $(ZONE),) $(if $(LOGGING_CONFIG),--logging-config $(LOGGING_CONFIG),)
\t@echo ""
\t@echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
\t@echo "  DRY-RUN complete. To apply these changes, run: make apply"
\t@echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
\t@echo ""

# Apply changes from local zones/ to providers
apply: validate
\t@echo ""
\t@echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
\t@echo "  APPLYING CHANGES TO LIVE DNS - This will modify DNS records!"
\t@echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
\t@echo ""
\t@QUIET=$(QUIET) DEBUG=$(DEBUG) octodns-gitops-sync --config config.yaml --doit $(if $(ZONE),--zone $(ZONE),) $(if $(FORCE),--force,) $(if $(LOGGING_CONFIG),--logging-config $(LOGGING_CONFIG),)
\t@echo ""
\t@echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
\t@echo "  Changes applied to live DNS"
\t@echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
\t@echo ""

# Check for drift: fails if live DNS differs from local zones
drift-check:
\t@QUIET=$(QUIET) DEBUG=$(DEBUG) octodns-gitops-drift --config config.yaml $(if $(ZONE),--zone $(ZONE),) $(if $(LOGGING_CONFIG),--logging-config $(LOGGING_CONFIG),)

# Query live DNS and compare with configured source (zones)
report:
\t@QUIET=$(QUIET) DEBUG=$(DEBUG) octodns-gitops-report --config config.yaml $(if $(ZONE),--zone $(ZONE),) $(if $(LOGGING_CONFIG),--logging-config $(LOGGING_CONFIG),)
"""


def main() -> int:
    """Output Makefile to stdout."""
    print(MAKEFILE_TEMPLATE)
    return 0


if __name__ == "__main__":
    sys.exit(main())
