"""Tests for bootstrap/makefile.py"""

import pytest
from io import StringIO
from unittest.mock import patch

from octodns_gitops.bootstrap.makefile import main, MAKEFILE_TEMPLATE


class TestMain:
    """Tests for the main() function."""

    def test_main_returns_zero(self):
        """main() should return 0 on success."""
        with patch("sys.stdout", new_callable=StringIO):
            result = main()
        assert result == 0

    def test_main_outputs_makefile(self):
        """main() should output the Makefile template to stdout."""
        output = StringIO()
        with patch("sys.stdout", output):
            main()

        result = output.getvalue()
        assert "Generated by octodns-gitops-init" in result

    def test_makefile_contains_targets(self):
        """The Makefile template should contain all expected targets."""
        assert "validate:" in MAKEFILE_TEMPLATE
        assert "plan:" in MAKEFILE_TEMPLATE
        assert "apply:" in MAKEFILE_TEMPLATE
        assert "drift-check:" in MAKEFILE_TEMPLATE
        assert "report:" in MAKEFILE_TEMPLATE
        assert "help:" in MAKEFILE_TEMPLATE

    def test_makefile_contains_octodns_gitops_commands(self):
        """The Makefile should use octodns-gitops CLI commands."""
        assert "octodns-gitops-validate" in MAKEFILE_TEMPLATE
        assert "octodns-gitops-sync" in MAKEFILE_TEMPLATE
        assert "octodns-gitops-drift" in MAKEFILE_TEMPLATE
        assert "octodns-gitops-report" in MAKEFILE_TEMPLATE

    def test_makefile_supports_zone_filter(self):
        """The Makefile should support ZONE= filtering."""
        assert "ZONE=" in MAKEFILE_TEMPLATE
        assert "--zone $(ZONE)" in MAKEFILE_TEMPLATE

    def test_makefile_supports_force_flag(self):
        """The Makefile should support FORCE=1 for apply."""
        assert "FORCE=" in MAKEFILE_TEMPLATE
        assert "--force" in MAKEFILE_TEMPLATE
